version: '3'

services:
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      ENVIRONMENT: "local"
    networks:
      - app-tier
    command: pipenv run python main.py
    volumes:
      - ./:/app

networks:
  app-tier:
    driver: bridge